export const PROVENANCE = Object.freeze({
  OFFICIAL_FACT: "OFFICIAL_FACT",
  USER_OBSERVATION: "USER_OBSERVATION",
  BROWSER_OBSERVATION: "BROWSER_OBSERVATION",
  EXTERNAL_VERIFICATION: "EXTERNAL_VERIFICATION",
  ANALYTICAL_INFERENCE: "ANALYTICAL_INFERENCE",
});

export const ANSWER_STATUS = Object.freeze({
  PASS: "PASS",
  FAIL: "FAIL",
  WARNING: "WARNING",
  UNKNOWN: "UNKNOWN",
  NOT_TESTED: "NOT_TESTED",
  NOT_APPLICABLE: "NOT_APPLICABLE",
  UNAVAILABLE: "UNAVAILABLE",
});

export const ANSWER_OUTCOME = Object.freeze({
  POSITIVE: "POSITIVE",
  ADVERSE: "ADVERSE",
  UNKNOWN: "UNKNOWN",
  OBSERVATION: "OBSERVATION",
  UNCLASSIFIED: "UNCLASSIFIED",
});

export const RULE_APPLICABILITY = Object.freeze({
  APPLICABLE: "APPLICABLE",
  NOT_APPLICABLE: "NOT_APPLICABLE",
  DEFERRED: "DEFERRED",
});

export const COMPARISON_OUTCOME = Object.freeze({
  MATCH: "MATCH",
  MISMATCH: "MISMATCH",
  UNRESOLVED: "UNRESOLVED",
  NOT_COMPARABLE: "NOT_COMPARABLE",
});

export const DIAGNOSTIC_STATE = Object.freeze({
  AVAILABLE: "AVAILABLE",
  PERMISSION_REQUIRED: "PERMISSION_REQUIRED",
  DENIED: "DENIED",
  UNSUPPORTED: "UNSUPPORTED",
  RUNNING: "RUNNING",
  COMPLETED_BY_USER: "COMPLETED_BY_USER",
  CANCELLED: "CANCELLED",
  ERROR: "ERROR",
});

export const DIAGNOSTIC_MODE = Object.freeze({
  COMPANION: "companion",
  TARGET: "target",
});

export const APP_STATUS = Object.freeze({
  BOOTING: "BOOTING",
  READY: "READY",
  ERROR: "ERROR",
});

export const NOT_VERIFIED_LABEL = "Not verified in the current dataset";

export const ANALYTICAL_QUALIFIER = "Analytical assessment; not a guarantee";
